name: "Mocker SPM CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.6'
      - name: Run Tests
        run: swift test

  linux-run-tests:
    name: Unit Tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.6'
      - name: Run Tests
        run: swift test
